from enum import StrEnum


class TaskState(StrEnum):
    ALARM_RECEIVED = "ALARM_RECEIVED"
    CONTEXT_COLLECTING = "CONTEXT_COLLECTING"
    EVIDENCE_REVIEW = "EVIDENCE_REVIEW"
    FIELD_EVIDENCE_PENDING = "FIELD_EVIDENCE_PENDING"
    HUMAN_DECISION = "HUMAN_DECISION"
    WORK_ORDER_DRAFTED = "WORK_ORDER_DRAFTED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    MAINTENANCE_PROCESSING = "MAINTENANCE_PROCESSING"
    RESULT_VALIDATION = "RESULT_VALIDATION"
    CLOSED = "CLOSED"
